### ISSUE TITLE
BpmnModdle is not a constructor

### ISSUE THREAD

**Issue by cxl-todd** [bpmn-io/bpmn-auto-layout#17]
I am trying to get auto layout to work, but I continue running into this error.

`BpmnModdle is not a constructor`

I am not doing anything with BpmnModdle. It is not included in my project explicitly. Please advise.

**Comment by nikku** [comment]
Please use the existing bug report template and provide the required information. Otherwise we won't be able to help you.

**Comment by barmac** [comment]
I am unable to reproduce the specific error that you are referring to. Cf. https://codesandbox.io/s/youthful-volhard-ffnb1?fontsize=14&hidenavigation=1&theme=dark

Feel free to reopen this issue when you find a way so that we can see the exact error. You can use CodeSandbox for that.
