### ISSUE TITLE
unknown type <bpmn:Definitions>

### ISSUE THREAD

**Issue by sanjay-thiyagarajan** [bpmn-io/bpmn-auto-layout#21]
![image](https://user-images.githubusercontent.com/42594454/143667765-f698c508-3f39-44c1-b029-a632ede68ecf.png)
The above error occurs when calling the function as instructed in the documentation.

Input XML : 
```
<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" 
		xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" 
		id="Definitions_1" targetNamespace="http://bpmn.io/schema/bpmn"><bpmn:process id="Process_1" isExecutable="false"><bpmn:endEvent id="endEvent2" name="end_component"></bpmn:endEvent><bpmn:startEvent id="startEvent3" name="start_component"></bpmn:startEvent><bpmn:sequenceFlow id="sequenceFlow1" sourceRef="startEvent3" targetRef="endEvent2" /></bpmn:process></bpmn:definitions>
```

I've tried renaming the XML parent tag to <bpmn:Definitions> too. It didn't work though.

**Comment by MaxTru** [comment]
Could you please use the issue template? In particular: please provide precise steps how to reproduce the issue. Thanks

**Comment by sanjay-thiyagarajan** [comment]
@MaxTru The library works very well when I run it locally. The problem arises when I try to use it through ResourceLoader in my PHP project. Is there anything which I should do, other than the code provided in the README in that case ?

**Comment by MaxTru** [comment]
From the error message I would assume that you pass a diagram file or string, which is not actually a BPMN XML. 

However, now it seems this is a problem of your setup and not of the library per se. Hence I would close this issue. Please feel free to re-open, if you observe a concrete bug.

For general questions, please also feel free to use our forum: https://forum.bpmn.io/
