### ISSUE TITLE
example.js not working

### ISSUE THREAD

**Issue by samuelT2** [bpmn-io/bpmn-auto-layout#25]
__Describe the Bug__

When running example.js, it produces an UnhandledPromiseRejectionWarning.

__Steps to Reproduce__

1. node ./example.js

__Expected Behavior__

Write console output and save the file.

__Fix__

Line 68, add await: `var layoutedDiagramXML = await autoLayout.layoutProcess(diagramXML);`

**Comment by marstamm** [comment]
Hi @samuelT2 ,

thank you for reporting this issue, I am able to reproduce the issue and created a #26 to fix it
