### ISSUE TITLE
Allow overriding default spacing configuration

### ISSUE THREAD

**Issue by sarialem** [bpmn-io/bpmn-auto-layout#28]
### Is your feature request related to a problem? Please describe.

The default separation configuration can be changed to have better arrows visibility in sequence flows, example displaying using bpmn-js:
<img width="533" alt="image" src="https://user-images.githubusercontent.com/55347464/226206644-480ad175-1448-4e1e-803d-5c964b643b1b.png">

After changing `iLevelSeparation` from 20 to 40:
<img width="628" alt="image" src="https://user-images.githubusercontent.com/55347464/226206721-0de0ed3f-2554-4b34-af75-0c3c1453d5ff.png">

### Describe the solution you'd like

To allow overriding the default config by passing an optional `config` map when initializing `AutoLayout`

**Comment by barmac** [comment]
The default spacing looks like a bug to me. I believe we should adopt the increased spacing as the built-in, and there's no need for custom configuration.

**Comment by sarialem** [comment]
This would work too, used your suggested approach in the PR
