### ISSUE TITLE
`TypeError: Cannot read properties of undefined (reading 'filter')`

### ISSUE THREAD

**Issue by corocoto** [bpmn-io/bpmn-auto-layout#43]
### Describe the Bug

I refactored [`example.js`](https://github.com/bpmn-io/bpmn-auto-layout/blob/main/example.js) imports. In the end, I run the script to see how the `layoutProcess` function will set di elements for the bpmn structure. But unfortunately, it throws an error:

```js
file:///home/corocoto/Documents/Github/bpmn-auto-layout/dist/index.esm.js:707
    const startingElements = flowElements.filter(el => {
                                          ^

TypeError: Cannot read properties of undefined (reading 'filter')
    at Layouter.createGridLayout (file:///home/corocoto/Documents/Github/bpmn-auto-layout/dist/index.esm.js:707:43)
    at Layouter.handlePlane (file:///home/corocoto/Documents/Github/bpmn-auto-layout/dist/index.esm.js:694:25)
    at Layouter.createGridLayout (file:///home/corocoto/Documents/Github/bpmn-auto-layout/dist/index.esm.js:732:14)
    at Layouter.handlePlane (file:///home/corocoto/Documents/Github/bpmn-auto-layout/dist/index.esm.js:694:25)
    at Layouter.layoutProcess (file:///home/corocoto/Documents/Github/bpmn-auto-layout/dist/index.esm.js:688:10)
    at async file:///home/corocoto/Documents/Github/bpmn-auto-layout/example.js:65:28
``` 

### Steps to Reproduce

1. Open [a test project in the Replit](https://replit.com/@corocoto/bpmn-auto-layout-di-error)
2. Click onto the "Run" button

### Expected Behavior

The script will print a new bpmn structure into a console and also will write it into `layouted.bpmn` file.

### Environment

- Host (Browser/Node version), if applicable: Node v20.11.1
- OS: Linux Mint 20.3 x86_64
- Library version: Latest

**Comment by corocoto** [comment]
## Additional information

Maybe it will be helpful to represent and visualize this schema. So, it looks like the next one:

1) The main structure:

![diagram](https://github.com/bpmn-io/bpmn-auto-layout/assets/37180024/c87fcfeb-fc66-4b7f-8eeb-5f490b845319)

2) subProcess (**Task_01g18mq** ) internal structure:

![subProcess-internal](https://github.com/bpmn-io/bpmn-auto-layout/assets/37180024/0be17caf-2e45-4259-9f8f-1bebd6d224a2)

**Comment by nikku** [comment]
I dropped the unmaintained example via https://github.com/bpmn-io/bpmn-auto-layout/commit/fbb021dcc759c2df089610b335e5bc9766ada54a.

If it was not working (layouting fails) then I'd assume it would be great to reproduce the error in a failing test case. We could take it from there.

**Comment by corocoto** [comment]
> I'd assume it would be great to reproduce the error in a failing test case

@nikku, done! https://github.com/bpmn-io/bpmn-auto-layout/pull/44

**Comment by nikku** [comment]
Thanks. A good start to fix this, some day, maybe.
