### ISSUE TITLE
Simple link event loop patterns are not well placed

### ISSUE THREAD

**Issue by till-stadtler** [bpmn-io/bpmn-auto-layout#48]
### Describe the Bug

Here are two rather simple examples of using link events for a loop pattern. The top part is the original version (by me), the bottom part it the layouted version. As seen in my version, the elements would fit well on a grid.

Example 1:
![image](https://github.com/user-attachments/assets/d1eb7cf8-2a24-4aa6-a806-7bfa052f141d)

Example 2:
![image](https://github.com/user-attachments/assets/8315d299-6cf6-43ff-ba40-e1a5a8015a19)

### Steps to Reproduce

Run the layouter with the examples above.

### Expected Behavior

I expect the layouter to roughly follow my original version. The "happy path" should not diverge:
The merging gateway should be added to the first row and not behind the link catch event.
![image](https://github.com/user-attachments/assets/737d7cfe-ecd9-48e6-9c0c-4ec5678d8b91)

In a post-processing step, the link catch event could be moved two grid spaces to the right.

### Environment

- Host: React App (node 20.13.1) in Chrome browser
- OS: Windows 11
- Library version: 0.5.0

**Comment by till-stadtler** [comment]
The following example seems to be closely related:
![image](https://github.com/user-attachments/assets/66ee2c99-c378-41f0-9a6e-df782d19e4ef)

The merging gateway could have been placed in the first row.

**Comment by till-stadtler** [comment]
I solved both issues on my local machine. I will explain more details later. We can also have a meeting to discuss this.

**Comment by till-stadtler** [comment]
I will try to communicate the steps that are necessary to fix this bug.

First issue:
The start event and link event are both "startingElements". They are directly added to the grid, the first element of startingElements on top, the second one directly below. In the current version, this depends on the order in the XML. 
**This should be improved by sorting the startingElements: any kind of start event should be added before intermediate events.**

startingElements is also used to create the "stack". 
**In this case, the sorting order needs to be reversed! The startingElement that was placed first should be the last element on the stack. We will pop() it and work with it, placing the next elements behind it. This ensure that we working with the element that we placed first.**

Regarding the two events at the end: The order of these also depend on the order in the XML. This could also be improved, but it is a broader topic, because entire "branches" behind a splitting element would need to be analyzed to improve the layout:
- check if a "branch" leads to an end event (needs a lot of tracing through all upcoming elements)
- check if a "branch" leads to an already placed (visited) element (sign of a loop, should be placed last)
- ...
For now, we should not focus on this too much.

Second issue:
The second issue is about the placement of a merging gateway. This is a complex topic, here is how I solved it:
- introduce a new array called "skipped". It will hold elements which outgoing elements have not all been placed yet
- these skipped elements can be revisited. We can loop through the outgoing elements again with no harm, trying to place missing outgoing elements
- we now have the stack and the skipped elements to work with. The stack is preferred, we will always work with the stack first, the skipped elements second
- a merging gateway is skipped if its incoming elements have not been placed yet. In non-loop cases, this allows us to place all elements using the stack first, resulting in us placing all incoming elements of that merging gateway. We can then find "the best" position of the merging gateway, taking the "smallest row" and "highest column + 1" into account. 
- In loop cases, we can run into the issue of not having a stack to work with, but still not having all incoming elements placed, and thus, we want to skip the merging gateway, but we must not. Instead, if we have no stack, we take the first skipped element, try to place its outgoing elements (we will skip it once again), but we will retry and eventually "force" the placement of the merging (looping) gateway
- If the merging gateway is an outgoing element from a splitting gateway, a different approach should be taken, looking for the next "empty row" behind the gateway

The "skipped" array will also play a role in the proper placement of splitting gateways.

**Comment by abdul99ahad** [comment]
Hi @till-stadtler,

Just checking if you have made any progress on this issue. If you're still working on it, that's great! If not, or if you need help, I’m happy to take it over and carry it forward. Please let me know how you’d like to proceed.
