### ISSUE TITLE
Placement of merging gateways and sequence flows going right to left

### ISSUE THREAD

**Issue by till-stadtler** [bpmn-io/bpmn-auto-layout#50]
### Describe the Bug

The following example has multiple issues:
- position of second splitting gateway which affects the position of the following task and the connecting sequence flow
- the "looping" sequence flow first goes up then left, causing sequence flows to overlap and cross each other
![image](https://github.com/user-attachments/assets/f38287bc-adf4-4ed6-934f-cf3f802f1e25)

Additionally, the placement of merging gateways (or other implicitly merging elements) often causes sequence flows going right to left:
![image](https://github.com/user-attachments/assets/f2b4e923-8f40-4e69-95c3-db5d1f9d9536)

### Steps to Reproduce

Layout the examples above.

### Expected Behavior

The position of the second splitting gateway could be improved, see issue #49.

Improving the "looping" sequence flow is related to the placement of merging gateways and elements which implicitly merge multiple sequence flows. With the current implementation, it is difficult to know if sequence flows going right to left are proper "loops" or simply caused by badly placed merging gateways/elements. 

Thus, my proposal is a combination of:
- fix the placement of merging gateways/elements (idea: skip placing merging gateways or elements until all "related" elements have been placed, or until no other element can be placed because they all come after the merging gateway/element (a proper loop), and then place the gateway/element to a position to the right off all related elements,)
- afterwards, we can assume that all sequence flows going right to left are part of proper loops. These sequence flows should leave the element to the right and then go **downwards**

### Environment

- Host: React App (node 20.13.1) in Chrome browser
- OS: Windows 11
- Library version: 0.5.0

**Comment by till-stadtler** [comment]
I solved this issue on my local machine. I will explain more details later. We can also have a meeting to discuss this.

**Comment by till-stadtler** [comment]
Nearly all issues described here would be solved with the solutions discussed in #48 and #49.

We can now make improvements on the waypoints used for sequence flows going right to left + bottom to top. With the proper placement of merging gateways, such sequence flows indicate a proper "loop". Thus, these sequence flows can now go down and left, rather than up and left. Like this, they will not overlap or cross other sequence flows as often. They might still cause trouble in certain edge cases. Here, the sorting of the outgoing elements behind a splitting element will help (making sure that gateways involved in loops are placed last and in an empty row.

**Comment by nikku** [comment]
Not addressed on current main, likely related to https://github.com/bpmn-io/bpmn-auto-layout/pull/68#issuecomment-2374445605.

![image](https://github.com/user-attachments/assets/6d1a1a27-0d95-4f60-bb11-5ec25326efb0)

I expect back and forward loops outside of the happy path to always go below other content.

**Comment by abdul99ahad** [comment]
> Not addressed on current main, likely related to [#68 (comment)](https://github.com/bpmn-io/bpmn-auto-layout/pull/68#issuecomment-2374445605).
> 
> ![image](https://private-user-images.githubusercontent.com/58601/370796093-6d1a1a27-0d95-4f60-bb11-5ec25326efb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyODA4MDksIm5iZiI6MTcyNzI4MDUwOSwicGF0aCI6Ii81ODYwMS8zNzA3OTYwOTMtNmQxYTFhMjctMGQ5NS00ZjYwLWJiMTEtNWVjMjUzMjZlZmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDE2MDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZDA2OWQxZWE3OTUwZTI3OTA5ZmZkYTYzZGM0NGJjZjgxMDUyZDljODNiOGFjYmU5ZDFlNDNhMTAwYzFjNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.19JRVC_U07wgwapHErFeYvSLvjLVZTerY5hs1P2Cf4A)
> 
> I expect back and forward loops outside of the happy path to always go below other content.

Noted, will create separate issue for this.

**Comment by nikku** [comment]
Also interested in getting @till-stadtler's feedback here, our options are:

### Alternative flow below happy path

![image](https://github.com/user-attachments/assets/61102e4f-0a1f-4e40-bfcd-a20729cdbbed)

### Alternative flow above happy path

![image](https://github.com/user-attachments/assets/ef5999e6-8b0a-4e8b-8c1f-edffa37cb9ba)

**Comment by till-stadtler** [comment]
Some quick thoughts:
* dX < 0, dY = 0: above
* else below
[In my PR](https://github.com/bpmn-io/bpmn-auto-layout/pull/56/files#diff-e8d7b0a12381f80b1bb9ab68dfa50905e87b6d00d94e4e09f35a61bd35a0b6b6), I made some changes to the layout util that are related to this question.

To differentiate between activities, events and gateways is also important, see PR. We don't want to "circle around" the gateway, if we can simply access it from the top or bottom.

**Comment by nikku** [comment]
@till-stadtler you suggest to "loop back" on top, and "loop forward" below? 

![image](https://github.com/user-attachments/assets/7bc3fd44-8da3-43ac-811f-d16722551bae)

Why? I'd consistently model happy path first, and everything else below. We'll otherwise run into https://github.com/bpmn-io/bpmn-auto-layout/issues/50#issuecomment-2374504074 and friends.

What I understand, and what we'd need to account for "sites used", and ensure flows don't cross (or otherwise intersect) when they don't share the same origin or target: 

![image](https://github.com/user-attachments/assets/1a31c63a-bc5e-43e3-9934-61ddd8b509f4)

**Comment by barmac** [comment]
Note that any outgoing connections in the upper direction shift the happy path down. So you cannot look at the very top of the diagram and see the desired process path, but rather needs to look slightly down. I'd rather have the loops always move to the bottom.

**Comment by nikku** [comment]
This issue is, to our knowledge, sufficiently addressed with the [recent release](https://github.com/bpmn-io/bpmn-auto-layout/blob/main/CHANGELOG.md#100).

Please open follow-ups with steps to reproduce.
