### ISSUE TITLE
Gateway placement happy path 

### ISSUE THREAD

**Issue by abdul99ahad** [bpmn-io/bpmn-auto-layout#63]
### Describe the Bug

Fails to layout (expected gateway to be on the happy path:

![image](https://github.com/user-attachments/assets/25efbc07-73f4-4b57-bd38-d101d468ca9e)

![image](https://github.com/user-attachments/assets/7609030d-70c3-4725-bfcb-2387b1dfede8)

### Steps to Reproduce

1. Model this 

[Playground for test ](https://philippfrom.me/bpmn-auto-layout-playground/)

### Expected Behavior

The model should model as in left. The gateway element should be in first row, currently it's modeled in reference with Start event, if there's no start event even then the gateway should be modeled correctly.

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

**Comment by abdul99ahad** [comment]
Resolved in #67

**Comment by nikku** [comment]
Cf. https://github.com/bpmn-io/bpmn-auto-layout/pull/68#issuecomment-2374445605 for potential follow-up.
