### ISSUE TITLE
Disconnected Elements placement

### ISSUE THREAD

**Issue by abdul99ahad** [bpmn-io/bpmn-auto-layout#64]
### Describe the Bug

Disconnected Elements (edge case?)

Fails to layout (remaining elements not placed): 

![image](https://github.com/user-attachments/assets/22a9215a-42ca-4898-84eb-8d03b98a5b18)

### Steps to Reproduce

1. Model this 

[Playground for test](https://philippfrom.me/bpmn-auto-layout-playground/)

### Expected Behavior

The model should render correctly. The deadlock occurs because the first element is both the only element in the stack and the looping element, causing it to return with no other elements left in the stack.

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

**Comment by nikku** [comment]
Test case added via https://github.com/bpmn-io/bpmn-auto-layout/commit/7c49736ca12493dae6826f8a5a2c5b870f33a1e8.
